webtalk_init -webtalk_dir E:/VHDL/Synt_CWT/Synt_CWT.sim/sim_1/behav/xsim/xsim.dir/ECG_cwt_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 30 15:04:53 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212132715_0_0_968" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "77e90b03-5c43-4176-a55f-2f71c6abfc8a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5511cce5ff824b4aaf9950744fc2a647" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5500U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "14.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "241 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "88.28_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14608_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4147692275 -regid "212132715_0_0_968" -xml E:/VHDL/Synt_CWT/Synt_CWT.sim/sim_1/behav/xsim/xsim.dir/ECG_cwt_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/VHDL/Synt_CWT/Synt_CWT.sim/sim_1/behav/xsim/xsim.dir/ECG_cwt_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/VHDL/Synt_CWT/Synt_CWT.sim/sim_1/behav/xsim/xsim.dir/ECG_cwt_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
